language: php

php:
  - '5.6'
  - '7.0'

before_install:
  - mv .env.example .env

install: 
  - composer install

script: 
  - php artisan key:generate
  - php artisan passport:install
  - vendor/bin/phpunit --debug

after_success:
  - travis_retry php vendor/bin/coveralls